### ISSUE TITLE
Не работает Планировщик

### ISSUE THREAD

**Issue by Joker-HD** [yenesey/Synapse#3]
Задачи в Планировщике не запускаются автоматом. В журнале нет строк о запуске.

**Comment by yenesey** [comment]
Прошу приложить выгрузку таблицы jobs
У меня отрабатывает Validate с разнообразными параметрами, например такой вариант
INSERT INTO jobs (
                     code,
                     last,
                     description,
                     enabled,
                     schedule,
                     params,
                     task,
                     id
                 )
                 VALUES (
                     0,
                     '2018-09-26 08:44',
                     NULL,
                     1,
                     '1,10,20,30 * * * * *',
                     '{"argv":{},"pp":{"email":[""],"print":""}}',
                     139,
                     205
                 );

**Comment by Joker-HD** [comment]
[jobs.txt](https://github.com/yenesey/Synapse/files/2418270/jobs.txt)

**Comment by yenesey** [comment]
не получается воспроизвести. 
"у меня все работает" (с)
попробуй добавить в jobs.js в строку 104 логирование внутрь 	return function(){
и для задания которое должно стартовать каждую секунду посмотри что происходит

**Comment by Joker-HD** [comment]
тогда лог отрабатывает, а потом задача выполняется

**Comment by yenesey** [comment]
Это означает, что не отрабатывает cron  - т.е. он не "дергает" задачу. А функционал выполнения задачи работает правильно.
Нужно посмотреть, как выглядит хранилище crons после загрузки модуля
У меня так (одна задача включена, одна выключена)
```Javascript
{ '75':
   CronJob {
     context: [Circular],
     _callbacks: [ [Function] ],
     onComplete: [Function],
     cronTime:
      { source: '0 30 9 * * *',
        second: [Object],
        minute: [Object],
        hour: [Object],
        dayOfMonth: [Object],
        month: [Object],
        dayOfWeek: [Object] },
     unrefTimeout: undefined,
     running: true,
     _timeout:
      Timeout {
        _called: false,
        _idleTimeout: 78988555,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 1111,
        _onTimeout: [Function: callbackWrapper],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 29,
        [Symbol(triggerId)]: 0 } },
  '205':
   CronJob {
     context: [Circular],
     _callbacks: [ [Function] ],
     onComplete: [Function],
     cronTime:
      { source: '1,10,20,30 * * * * *',
        second: [Object],
        minute: [Object],
        hour: [Object],
        dayOfMonth: [Object],
        month: [Object],
        dayOfWeek: [Object] },
     unrefTimeout: undefined } }

```

**Comment by Joker-HD** [comment]
Нужно посмотреть, как выглядит хранилище crons после загрузки модуля.
КАК????

**Comment by yenesey** [comment]
Расписано выше. Обнови

**Comment by Joker-HD** [comment]
{ '76': 
   CronJob {
     context: [Circular],
     _callbacks: [ [Function] ],
     onComplete: [Function],
     cronTime: 
      { source: '* * * * * *',
        second: [Object],
        minute: [Object],
        hour: [Object],
        dayOfMonth: [Object],
        month: [Object],
        dayOfWeek: [Object] },
     unrefTimeout: undefined,
     running: true,
     _timeout: 
      Timeout {
        _called: false,
        _idleTimeout: 374848026,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 6076,
        _onTimeout: [Function: callbackWrapper],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(asyncId)]: 31,
        [Symbol(triggerId)]: 0 } } }

**Comment by yenesey** [comment]
А что если удалить все задачи, и добавлять по одной, начиная с простейших, типа validate. 
В случае чего, можно будет вернуть их с помощью скрипта который здесь прикреплен

**Comment by Joker-HD** [comment]
у меня и так одна задача на dev

**Comment by Joker-HD** [comment]
что означает эта ошибка?
./client_source/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@vue/app" relative to directory "C:\\xtech\\synapse_dev\\client_source"
    at C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xtech\synapse_dev\node_modules\babel-loader\lib\index.js:50:20)
    at C:\xtech\synapse_dev\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\xtech\synapse_dev\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
 @ multi @/hmr-iexplore @/main.js synapse[1]
./client_source/hmr-iexplore.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@vue/app" relative to directory "C:\\xtech\\synapse_dev\\client_source"
    at C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\xtech\synapse_dev\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\xtech\synapse_dev\node_modules\babel-loader\lib\index.js:50:20)
    at C:\xtech\synapse_dev\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\xtech\synapse_dev\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
 @ multi @/hmr-iexplore @/main.js synapse[0]

**Comment by yenesey** [comment]
npm install

**Comment by Joker-HD** [comment]
пошло после полного обновления

**Comment by yenesey** [comment]
и джобы тоже?

**Comment by yenesey** [comment]
вот ну не гад ли ты....
